apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-data
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: visualizer
spec:
  storageClassName: manual
  volumeName: grafana-data
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: visualizer
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=
