apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /data/prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: monitoring
spec:
  storageClassName: manual
  volumeName: prometheus-data
  resources:
    requests:
      storage: 512Mi
  accessModes:
    - ReadWriteOnce
